// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiVGKGe12h_I9YwHkuMZUn4c98QeyT5E0',
    appId: '1:203911321036:web:c9933cdae65b0bd916f969',
    messagingSenderId: '203911321036',
    projectId: 'plasma-creek-491403-e8',
    authDomain: 'plasma-creek-491403-e8.firebaseapp.com',
    databaseURL: 'https://plasma-creek-491403-e8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'plasma-creek-491403-e8.firebasestorage.app',
    measurementId: 'G-JRJMHFF276',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9hiNuZwKsEJJgjElucz74zH-SdrHk-ms',
    appId: '1:203911321036:android:3e39e63aa06dbd5b16f969',
    messagingSenderId: '203911321036',
    projectId: 'plasma-creek-491403-e8',
    databaseURL: 'https://plasma-creek-491403-e8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'plasma-creek-491403-e8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1tCRXyLbhs6uVcRdf_78ATqmMRrTNNWk',
    appId: '1:203911321036:ios:5aa13911b0e1290216f969',
    messagingSenderId: '203911321036',
    projectId: 'plasma-creek-491403-e8',
    databaseURL: 'https://plasma-creek-491403-e8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'plasma-creek-491403-e8.firebasestorage.app',
    iosBundleId: 'com.example.andAnotherOne',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1tCRXyLbhs6uVcRdf_78ATqmMRgit add .'
        'rTNNWk',
    appId: '1:203911321036:ios:5aa13911b0e1290216f969',
    messagingSenderId: '203911321036',
    projectId: 'plasma-creek-491403-e8',
    databaseURL: 'https://plasma-creek-491403-e8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'plasma-creek-491403-e8.firebasestorage.app',
    iosBundleId: 'com.example.andAnotherOne',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiVGKGe12h_I9YwHkuMZUn4c98QeyT5E0',
    appId: '1:203911321036:web:5eebb0c6e2e579ae16f969',
    messagingSenderId: '203911321036',
    projectId: 'plasma-creek-491403-e8',
    authDomain: 'plasma-creek-491403-e8.firebaseapp.com',
    databaseURL: 'https://plasma-creek-491403-e8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'plasma-creek-491403-e8.firebasestorage.app',
    measurementId: 'G-SYN0ZV21ZT',
  );
}
